import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describeAppServerProtocol } from '../src/native/app-server/protocol-contract.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputDirectory = resolve(root, 'src/native/app-server/generated')
const clientPath = resolve(outputDirectory, 'client.ts')
const schemaPath = resolve(outputDirectory, 'protocol.schema.json')
const protocol = describeAppServerProtocol()
const methods = protocol.methods.map(method => method.method)
const generatedMethods = `[\n${methods.map(method => `  '${method}',`).join('\n')}\n]`

const client = `// Generated by scripts/generate-app-server-contract.ts. Do not edit directly.\n\nexport const GENERATED_APP_SERVER_PROTOCOL_VERSION = ${JSON.stringify(protocol.protocolVersion)} as const\n\nexport const GENERATED_APP_SERVER_METHODS = ${generatedMethods} as const\n\nexport type GeneratedAppServerMethod = typeof GENERATED_APP_SERVER_METHODS[number]\n\nexport interface GeneratedAppServerTransport {\n  call<T>(method: GeneratedAppServerMethod, params?: unknown): Promise<T>\n}\n\nexport function createGeneratedAppServerClient(transport: GeneratedAppServerTransport) {\n  return {\n    call<T>(method: GeneratedAppServerMethod, params?: unknown): Promise<T> {\n      return transport.call<T>(method, params)\n    },\n  }\n}\n`

const schema = `${JSON.stringify({
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://owlcoda.dev/schemas/app-server-protocol.json',
  title: 'OwlCoda App Server JSON-RPC Request',
  type: 'object',
  properties: {
    jsonrpc: { const: '2.0' },
    id: { oneOf: [{ type: 'string' }, { type: 'number' }] },
    method: { type: 'string', enum: methods },
    params: { oneOf: [{ type: 'object' }, { type: 'array' }] },
  },
  required: ['jsonrpc', 'id', 'method'],
  additionalProperties: false,
  $defs: {
    eventEnvelope: {
      type: 'object',
      properties: {
        schemaVersion: { const: 1 },
        eventId: { type: 'string' },
        sequence: { type: 'integer', minimum: 1 },
        occurredAt: { type: 'string', format: 'date-time' },
        type: { type: 'string' },
        projectId: { type: 'string' },
        workspaceId: { type: 'string' },
        payload: { type: 'object' },
        artifactRefs: { type: 'array', items: { type: 'string' } },
      },
      required: [
        'schemaVersion',
        'eventId',
        'sequence',
        'occurredAt',
        'type',
        'projectId',
        'workspaceId',
        'payload',
        'artifactRefs',
      ],
      additionalProperties: true,
    },
  },
  'x-owlcoda-protocol-version': protocol.protocolVersion,
  'x-owlcoda-method-contracts': protocol.methods,
}, null, 2)}\n`

const outputs = [[clientPath, client], [schemaPath, schema]] as const
if (process.argv.includes('--check')) {
  const drifted = outputs.filter(([path, expected]) => !existsSync(path) || readFileSync(path, 'utf8') !== expected)
  if (drifted.length > 0) {
    console.error(`Generated App Server contract drift: ${drifted.map(([path]) => path).join(', ')}`)
    process.exitCode = 1
  }
} else {
  mkdirSync(outputDirectory, { recursive: true })
  for (const [path, contents] of outputs) writeFileSync(path, contents)
  console.log(`Generated ${outputs.length} App Server contract artifacts.`)
}
